/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package projetoLogin;

import java.sql.Connection;

public class App {

    public static void main(String[] args) {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        CriarTabela.criarTabelaUsuarios(conexao);
        // System.out.println(ListarUsuarios.listarUsuarios(conexao));

        InserirUsuario.inserirUsuario(conexao, "leo", "senhabanana");
        
        //DeletarUsuario.deletarUsuario(conexao, 1);
        
        System.out.println(ListarUsuarios.listarUsuarios(conexao));
    }
}

