/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetoLogin;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author PEDROHENRIQUECAUSSIP
 */
public class TelaLogin extends javax.swing.JFrame {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usuario = new javax.swing.JLabel();
        campoUSUARIO = new javax.swing.JTextField();
        senha = new javax.swing.JLabel();
        campoSENHA = new javax.swing.JPasswordField();
        botaoENTRAR = new javax.swing.JButton();
        botaoREGISTRAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        usuario.setText("LOGIN");

        campoUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoUSUARIOActionPerformed(evt);
            }
        });

        senha.setText("SENHA");

        campoSENHA.setText("usahsuahsa");

        botaoENTRAR.setText("ENTRAR");
        botaoENTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoENTRARActionPerformed(evt);
            }
        });

        botaoREGISTRAR.setText("REGISTRAR");
        botaoREGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoREGISTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(senha))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(usuario))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoREGISTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(botaoENTRAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoSENHA)
                            .addComponent(campoUSUARIO))))
                .addContainerGap(150, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoSENHA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(botaoENTRAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoREGISTRAR)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoREGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoREGISTRARActionPerformed
        String usuario = campoUSUARIO.getText();
        String senha = new String(campoSENHA.getPassword());
        
        boolean sucesso = InserirUsuario.inserirUsuario(conexao, usuario, senha);
        
         if(sucesso == true){
           JOptionPane.showMessageDialog(this, "Usuario Registrado","Registro",JOptionPane.DEFAULT_OPTION);
        }else{
            JOptionPane.showMessageDialog(this, "Usuario Ja Existe","Erro",JOptionPane.ERROR);
        }
    }//GEN-LAST:event_botaoREGISTRARActionPerformed

    private void campoUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoUSUARIOActionPerformed

    private void botaoENTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoENTRARActionPerformed
        String usuario = campoUSUARIO.getText();
        String senha = new String(campoSENHA.getPassword());
        
        if(Login.validarLogin(usuario,senha)){
            JOptionPane.showMessageDialog(this,"Login bem Sucedido");
            new TelaInicial().setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Usuario ou senha Incorretos");
        }
    }//GEN-LAST:event_botaoENTRARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoENTRAR;
    private javax.swing.JButton botaoREGISTRAR;
    private javax.swing.JPasswordField campoSENHA;
    private javax.swing.JTextField campoUSUARIO;
    private javax.swing.JLabel senha;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
